version: "2"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml   #prometheus主配置文件
      # - /data/prometheus/prometheus-data:/prometheus  #数据存储映射  chmod 777
      # - /data/prometheus/conf:/etc/prometheus/conf   #prometheus子配置文件路径
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'    #加载主配置文件
      - '--storage.tsdb.path=/prometheus'    #启动数据持久存储
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
        # volumes:
      # - /data/grafana/grafana.ini:/etc/grafana/grafana.ini #grafana配置文件
      # - /data/grafana/grafana_data:/var/lib/grafana   #数据存储映射 chmod 777
    restart: always
